apiVersion: v1
kind: ServiceAccount
metadata:
  name: osvbng-sriov-device-plugin
  namespace: kube-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: osvbng-sriov-device-plugin
  namespace: kube-system
  labels:
    app.kubernetes.io/name: sriov-network-device-plugin
    app.kubernetes.io/part-of: osvbng
    app.kubernetes.io/version: v3.11.0
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: osvbng-sriov-device-plugin
  template:
    metadata:
      labels:
        app.kubernetes.io/name: osvbng-sriov-device-plugin
        app.kubernetes.io/part-of: osvbng
    spec:
      serviceAccountName: osvbng-sriov-device-plugin
      hostNetwork: true
      nodeSelector:
        osvbng.infinitydon.com/dpdk-ha: "true"
      containers:
        - name: sriov-device-plugin
          image: ghcr.io/k8snetworkplumbingwg/sriov-network-device-plugin:v3.11.0@sha256:7c5901727d4500f103f038c178b41dc6450afa6f324306c1973495c9a7c4f5a5
          imagePullPolicy: IfNotPresent
          args:
            - --config-file=/etc/pcidp/config.json
            - --resource-prefix=qemu-virtio-dpdk.dev
            - --log-dir=/var/log
            - --log-level=4
          securityContext:
            privileged: true
          resources:
            requests:
              cpu: 100m
              memory: 40Mi
            limits:
              cpu: 500m
              memory: 200Mi
          volumeMounts:
            - name: devicesock
              mountPath: /var/lib/kubelet/device-plugins
            - name: plugins-registry
              mountPath: /var/lib/kubelet/plugins_registry
            - name: config
              mountPath: /etc/pcidp
              readOnly: true
            - name: device-info
              mountPath: /var/run/k8s.cni.cncf.io/devinfo/dp
            - name: log
              mountPath: /var/log
      volumes:
        - name: devicesock
          hostPath:
            path: /var/lib/kubelet/device-plugins
        - name: plugins-registry
          hostPath:
            path: /var/lib/kubelet/plugins_registry
        - name: config
          configMap:
            name: osvbng-sriovdp-config
        - name: device-info
          hostPath:
            path: /var/run/k8s.cni.cncf.io/devinfo/dp
            type: DirectoryOrCreate
        - name: log
          hostPath:
            path: /var/log
