osvbng:
  nodeSelector:
    kubernetes.io/hostname: ebpf-bng-node-02
  core:
    address: 192.168.88.11/24
    nextHop: 192.168.88.1
  cgnat:
    outsideAddresses:
      - 192.168.88.12
      - 192.168.88.13
      - 192.168.88.14
      - 192.168.88.15
  ha:
    enabled: true
    nodeId: bng-b
    peerAddress: osvbng.osvbng-ha-a.svc.cluster.local:50051
    srg:
      priority: 90
      preempt: false

bngblaster:
  enabled: false

trafficTest:
  enabled: false

