apiVersion: v2
name: osvbng-mcp-aiops
description: Agentgateway and ToolHive platform for osvbng MCP operations
type: application
version: 0.4.7
appVersion: "0.2.13"
kubeVersion: ">=1.32.0-0"
dependencies:
  - name: agentgateway
    version: v1.4.0
    repository: oci://cr.agentgateway.dev/charts
    condition: agentgateway.enabled
  - name: toolhive-operator
    version: 0.40.1
    repository: oci://ghcr.io/stacklok/toolhive
    condition: toolhive-operator.enabled
  - name: open-webui
    version: 15.2.0
    repository: https://helm.openwebui.com
    condition: open-webui.enabled
