apiVersion: v2
name: osvbng-mcp-aiops
description: Agentgateway and ToolHive platform for osvbng MCP operations
type: application
version: 0.1.2
appVersion: "0.1.1"
kubeVersion: ">=1.32.0-0"
dependencies:
  - name: agentgateway
    version: v1.4.0
    repository: oci://cr.agentgateway.dev/charts
    condition: agentgateway.enabled
  - name: toolhive-operator
    version: 0.40.1
    repository: oci://ghcr.io/stacklok/toolhive
    condition: toolhive-operator.enabled
