osvbng:
  core:
    installDefaultRoute: false
  bgp:
    enabled: true
    advertiseSubscriberPrefix: false
    localAs: 65010
    peerAs: 65020
    cgnatPrefix: 100.64.100.0/24
    bfd: false
    neighbors:
      - name: frr-a
        address: 172.31.255.4
      - name: frr-b
        address: 172.31.255.5
  cgnat:
    proxyArp: false
    outsideAddresses:
      - 100.64.100.0/24
  ha:
    enabled: true
    members:
      - nodeId: bng-a
        coreAddress: 172.31.255.2/29
        priority: 100
        preempt: false
      - nodeId: bng-b
        coreAddress: 172.31.255.3/29
        priority: 90
        preempt: false
    srg:
      interfaces:
        - access
      networks:
        - prefix: 100.64.100.0/24

radius:
  enabled: true
  existingSecret: osvbng-radius
  autoProvisionSubscriberUsers: true
  subscriberCapacity: 20
